### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by KurtPachinger** [KurtPachinger/vlay-gpr#1]
### bug
- [x] cubemap: texture has recurring pattern/hole across seeds
- [x] cubemap: picker sort inconsistent (1vs6)
- [x] seed: RNG/1e5 (unhelpful?)
- [x] CSG subtract: complex intersections have triangle soup, like bitwise XOR (test 0.5:6 and 0.66:9) https://github.com/KurtPachinger/vlay-gpr/issues/4#issuecomment-1245146751 https://github.com/KurtPachinger/vlay-gpr/commit/5993ecba1c25b83519cfd1f7537d0b26163129a5  https://github.com/KurtPachinger/vlay-gpr/commit/6d8e4d4018ffb059f8fe084657d4fa9eb2fa6380 https://github.com/KurtPachinger/vlay-gpr/commit/27729f267c41829d3de4efd542797c4d5b36f5c8
    - vertices are thrashed by .multiplyScalar(1.01) and .lerp()
    - ineffective: needsUpdate, async/await... 
    - effective: excessive extrusion, hull, transform (i.e. precision-related)
    - try other Vector3() methods or direct vertex multiplication or a setTimeOut...
- [x] light (inner used to cast shadows like god-ray)
- [x] fix normals: geo.computeVertexNormals() geo.computeFaceNormals()
- [x] window.onResize causes group.out to disappear (pos, neg, env, geo...) (requestAnimationFrame)
- [x] pos/neg tolerance: update biased to positive, with no filter for mid-range values
- [x] ~~shadow acne~~
- [ ] tweak tolerance
  - [ ] wrap() vertexColor is too subtle now (or broken)
  - [ ] segs() => profile(): reduce positive, increase system
  - [ ] env.lerp(pos, avg) can exceed 2 on grid
  - [ ] expose depth range to dat.gui
- [ ] gcut init with img/seed: overwritten uid material reference, or polymorphic binary checkbox (confused call invocation)
- [ ] abort same uid/uei: ignores img extensions & edited files

### performance
- [x] async progress: abort/regress
- [x] renderer.setAnimationLoop()
- [x] geometry index/merge better (renderer.info.render.calls) https://github.com/KurtPachinger/vlay-gpr/commit/b0ac197cbaca3bd8fc394665af477bdd03c43cfd
   - [x] merge full array once (~~unless abort~~): BufferGeometryUtils.mergeBufferGeometries()
   - [x] delete all attributes but position until Mesh
   - [x] OR at least color() before mergeVertices()
   - [ ] mipmap: morph > blurs[] store ctx, data, [faster access](https://gist.github.com/postspectacular/bea4fdbaa1479cc11a064e453dd7fe17)

### enhancement
- [x] depth mesh: from cubemaps or noise (OpenCV=>point/path)  https://github.com/KurtPachinger/vlay-gpr/issues/7#issuecomment-1255232631
  - [x] sample rgb area average
  - [x]  Perlin noise
  - [x] game of life: layer depth and sample resistance affects alpha/radius of process n
- [x] depth mesh: proc setting :: planet formation https://github.com/KurtPachinger/vlay-gpr/issues/7#issuecomment-1255232424
    - [x] averages more (neg => pos) with iteration
    - [x] classify face segments relative to overall feature ratio (pos/neg)
    - [x] secondary criteria (i.e. distance, defects length, weighted distribution...) https://github.com/KurtPachinger/vlay-gpr/issues/7#issuecomment-1255232788
      - [x] non-system: type dots (cloud, rock, pond) favor short/close (<3, <avg) 
      - [x] system: type path (cave, mount, pipe) favor variety 
      - [x] convex hull: unite forms (collapse, metaball, marching cube)
   - [x] ~~detail: LOD, tesselate, decimate, tube self-intersect~~ https://github.com/KurtPachinger/vlay/commit/2e80360784b0b68d2ea1406f63be28140dd27de2
   - [ ] segs: unit() => multiplyScalar(1+c.scale/2)
- [ ] cubemap: 
    - [x] input crop: file count or aspect 1.3
    - [x] layout as cross
    - [x] apply texture to elevate/CSG (resize to icosahedron and MultiplyBlend?)
    - [x] raycast vertexColor (origin)
    - [x] raycast vertexColor (face normal) https://github.com/KurtPachinger/vlay/commit/0e7b080f24d0d56df4af25f30beb7458fd5ef512
    - [x] ~~use CubeTexture / CubeTextureLoader (requires same size, dataURI, etc..)~~
    - [ ] geo material: bumpmap, map (convex?)
    - [ ] multiple: distribute offsets to altitudes of segs
- [x] demo
   - [ ] secondary geometry: torus knot, teapot
   - [ ] Portal-type CSG projectile (to enter planet core)  https://github.com/KurtPachinger/vlay-gpr/issues/7#issuecomment-1255232167
   - [ ] [FirstPersonControls](https://threejs.org/docs/#examples/en/controls/FirstPersonControls) and/or [Octree FPS collisions](https://threejs.org/examples/games_fps.html) and/or [rapier physics](https://github.com/pmndrs/react-three-rapier)
   - [ ] advanced: materials/transitions
   - [ ] animated targets: texture/model
   - [ ] use as base to animate emotion, focal jitter, or some other environmental cue
- [x] Points emit from "med" defects:
   - [x] static: dissolve constellation
   - [ ] dynamic: weather/swarm(?) https://github.com/KurtPachinger/vlay-gpr/commit/2a4ecf145d136ce5effcc8c12632bce2140237c4
- [ ] r3f:
   - [x] state.performance.regress()
   - [ ] ref library: seed defects, or geometry https://github.com/KurtPachinger/vlay-map/commit/0211aa573285885f1325f29a4171ccc9d5bbeb0f
   - [ ] component allows multiple planetary bodies

**Comment by KurtPachinger** [comment]
CSG subtract projectile
![geometry-destroy](https://user-images.githubusercontent.com/48163461/191794236-d70c0a41-d678-43de-a0ab-46fae0dbd739.png)
